# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_aggregator_development 

test:
  <<: *default
  database: seu_app_test

production:
  <<: *default
  database: news-aggregator-db
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

queue:
  production:
    <<: *production


cable: *production