# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_aggregator_development 

test:
  <<: *default
  database: news_aggregator_test

# Opção 1: Com DATABASE_URL (mais simples para o Render)
production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


  production:
    <<: *production

cable:
  production:
    <<: *production