
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: news_aggregator_development

test:
  <<: *default
  database: news_aggregator_test

production: &production
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable: *production

queue: *production